# Generated by Django 4.1.3 on 2023-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='referral_money',
            field=models.BigIntegerField(default=True),
        ),
    ]
